path: /home/sn3007/FootballPassPrediction/downloads/trackletframes-2.5k/
train: images/train #relative to path
val: images/val #relative to path

# Classes
nc: 2  # number of classes
names: ['Player', 'Football']  # class names
