# YOLOv8
# path: /home/sn3007/FootballPassPrediction/downloads/trackletframes-2.5k/
# train: images/train #relative to path
# val: images/val #relative to path

#YOLOv7
train: downloads/trackletframes-2.5k/images/train
val: downloads/trackletframes-2.5k/images/val

# Classes
nc: 2  # number of classes
names: ['Player', 'Football']  # class names
